// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GraphicCalc(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GraphicCalc'](arg1, arg2, arg3, arg4, arg5);
}

export function Greet(arg1, arg2) {
  return window['go']['main']['App']['Greet'](arg1, arg2);
}

export function HistoryClean() {
  return window['go']['main']['App']['HistoryClean']();
}

export function HistoryRead() {
  return window['go']['main']['App']['HistoryRead']();
}
