// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GraphicCalc(arg1:string,arg2:number,arg3:number):Promise<main.GraphData>;

export function Greet(arg1:string,arg2:number):Promise<string>;

export function HistoryClean():Promise<void>;

export function HistoryRead():Promise<Array<string>>;
