// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Graph(arg1:string,arg2:number):Promise<number>;

export function Greet(arg1:string,arg2:number):Promise<string>;
