// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Graph(arg1, arg2) {
  return window['go']['main']['App']['Graph'](arg1, arg2);
}

export function Greet(arg1, arg2) {
  return window['go']['main']['App']['Greet'](arg1, arg2);
}
